apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lab02-vllm
  namespace: lab02-kubernetes-llm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: lab02-vllm
